baseURL: "/"
title: "Invisiblends"
description: "Where Ends Meet"
copyright: "Copyright © 2020; All rights reserved"
languageCode: "en-us"
DefaultContentLanguage: "en"
paginate: "5"
# googleAnalytics: "UA-XXXX"
# DisqusShortname: ""

MetaDataFormat: "yaml"
canonifyURLs: "false"
enableEmoji: "true"
enableRobotsTXT: "true"
# enableInlineShortcodes: "true"

params:
   
